<?xml version="1.0" encoding="UTF-8"?>
<!--

    ==========================================================================================
    =                   JAHIA'S DUAL LICENSING - IMPORTANT INFORMATION                       =
    ==========================================================================================

                                    http://www.jahia.com

        Copyright (C) 2002-2016 Jahia Solutions Group SA. All rights reserved.

        THIS FILE IS AVAILABLE UNDER TWO DIFFERENT LICENSES:
        1/GPL OR 2/JSEL

        1/ GPL
        ==================================================================================

        IF YOU DECIDE TO CHOOSE THE GPL LICENSE, YOU MUST COMPLY WITH THE FOLLOWING TERMS:

        This program is free software: you can redistribute it and/or modify
        it under the terms of the GNU General Public License as published by
        the Free Software Foundation, either version 3 of the License, or
        (at your option) any later version.

        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with this program. If not, see <http://www.gnu.org/licenses />.


        2/ JSEL - Commercial and Supported Versions of the program
        ===================================================================================

        IF YOU DECIDE TO CHOOSE THE JSEL LICENSE, YOU MUST COMPLY WITH THE FOLLOWING TERMS:

        Alternatively, commercial and supported versions of the program - also known as
        Enterprise Distributions - must be used in accordance with the terms and conditions
        contained in a separate written agreement between you and Jahia Solutions Group SA.

        If you are unsure which license is appropriate for your use,
        please contact the sales department at sales@jahia.com.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>jahia-modules</artifactId>
        <groupId>org.jahia.modules</groupId>
        <version>8.1.5.0</version>
    </parent>
    <groupId>org.jahia.community</groupId>
    <artifactId>content-integrity</artifactId>
    <name>Content Integrity</name>
    <version>4.0.0-SNAPSHOT</version>
    <packaging>bundle</packaging>
    <description>Scans the JCR repository of a Jahia server to detect the inconsistent content, and fixes it</description>

    <properties>
        <!-- serverSettings: the node which issues the tools token of the JCR browser links is declared in its templates -->
        <jahia-depends>default,graphql-dxm-provider,serverSettings</jahia-depends>
        <jahia-module-type>system</jahia-module-type>
        <jahia-deploy-on-site>system</jahia-deploy-on-site>
        <export-package>org.jahia.modules.contentintegrity.api,
            org.jahia.modules.contentintegrity.services.impl,
            org.jahia.modules.contentintegrity.taglib</export-package>
        <!--
        Built against Jahia 8.1.5 to run on 8.1.5 and later. Jahia 8.1 provides graphql-java 13, graphql-java-annotations
        7.2.1 and graphql-dxm-provider 2.x; Jahia 8.2 provides graphql-java 21, graphql-java-annotations 21.1 and
        graphql-dxm-provider 3.x. The generated ranges cover 8.1 only, so these imports are widened to both lines.
        -->
        <import-package>graphql;version="[13.0,22)",
            graphql.annotations.annotationTypes;version="[7.2,22)",
            org.jahia.modules.graphql.provider.dxm;version="[2.3,4)",
            org.jahia.modules.graphql.provider.dxm.node;version="[2.3,4)",
            org.jahia.modules.graphql.provider.dxm.util;version="[2.3,4)"</import-package>
        <graphql-dxm-provider.version>2.3.0</graphql-dxm-provider.version>
        <external-provider.version>4.0.0</external-provider.version>
        <yarn.arguments>build:production</yarn.arguments>
    </properties>

    <scm>
        <connection>scm:git:git@github.com:Jahia/content-integrity</connection>
        <developerConnection>scm:git:git@github.com:Jahia/content-integrity</developerConnection>
        <url>https://github.com/Jahia/content-integrity</url>
        <tag>HEAD</tag>
    </scm>

    <repositories>
        <repository>
            <id>jahia-public</id>
            <name>Jahia Public Repository</name>
            <url>https://devtools.jahia.com/nexus/content/groups/public</url>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <distributionManagement>
        <repository>
            <id>ps-releases</id>
            <url>https://devtools.jahia.com/nexus/content/repositories/jahia-professional-services-public-repository</url>
        </repository>
        <snapshotRepository>
            <id>ps-snapshots</id>
            <url>https://devtools.jahia.com/nexus/content/repositories/jahia-professional-services-private-repository</url>
        </snapshotRepository>
    </distributionManagement>

    <build>
        <plugins>
            <!-- Removes the built React application, which is generated in the sources -->
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>src/main/resources/javascript/apps</directory>
                            <includes>
                                <include>*</include>
                            </includes>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Karaf-Commands>*</Karaf-Commands>
                        <!-- Read at runtime: the version is logged with each scan and stored on the scan reports -->
                        <Content-Integrity-Version>${project.version}</Content-Integrity-Version>
                    </instructions>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.15.0</version>
                <executions>
                    <execution>
                        <id>npm install node and yarn</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>install-node-and-yarn</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>v22.19.0</nodeVersion>
                            <yarnVersion>v1.22.22</yarnVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>yarn install</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>yarn</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>yarn build</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>yarn</goal>
                        </goals>
                        <configuration>
                            <arguments>${yarn.arguments}</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.apache.karaf.shell</groupId>
            <artifactId>org.apache.karaf.shell.console</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jahia.modules</groupId>
            <artifactId>external-provider</artifactId>
            <version>${external-provider.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jahia.modules</groupId>
            <artifactId>graphql-dxm-provider</artifactId>
            <version>${graphql-dxm-provider.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.github.graphql-java</groupId>
            <artifactId>graphql-java-annotations</artifactId>
            <version>${graphql-java-annotations.version}</version>
            <scope>provided</scope>
        </dependency>
        <!-- The scan subscription is a Publisher. Jahia 8.1.5 and 8.2 both provide RxJava 2.1.5 and Reactive Streams 1.0.2 -->
        <dependency>
            <groupId>io.reactivex.rxjava2</groupId>
            <artifactId>rxjava</artifactId>
            <version>2.1.5</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.reactivestreams</groupId>
            <artifactId>reactive-streams</artifactId>
            <version>1.0.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.servlet.jsp</groupId>
            <artifactId>jsp-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
