configuration.name=Content Integrity
configuration.description=Configuration of the content-integrity module
ui.name=contentIntegrity.ui
ui.description=Implementation to use for the UI. Choosing "default" means using the javascript UI until the React one becomes production ready
ui.value.default=Default
ui.value.js=Javascript
ui.value.react=React
